site_name: OnTrack Hockey

theme:
  name: readthedocs

nav:
  - Home: index.md
  - API:
      - Players: api/players.md
      - Teams: api/teams.md
      - Roster: api/roster.md
      - Divisions: api/divisions.md
      - Leagues: api/leagues.md
      - Games: api/games.md
      - Game Events: api/game_events.md
